server:
  port: 8006

spring:
  profiles:
    active:
      - dog
      - en
      - dev
  messages:
    basename: messages/messages
  banner:
    image:
      location: B&W.jpg
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:bd_job

jbs:
  username: YMLUserName
  password: YMLPassword
  jdbcurl: YMLUrl

---
spring:
  config:
    activate:
      on-profile: prod
jbs:
  username: YMLProdUserName
  password: YMLProdPassword
  jdbcurl: YMLProdUrl

---
spring:
  config:
    activate:
      on-profile: dev
jbs:
  username: YMLDevUserName
  password: YMLDevPassword
  jdbcurl: YMLDevUrl

