server:
  port: 8006

spring:
  profiles:
    active:
      - en
      - dev
      - springdatajpa
  messages:
    basename: messages/messages
  banner:
    image:
      location: B&W.jpg
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    #ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: database_create.sql
  datasource:
    url: jdbc:mysql://localhost:3306/jbsdatabase
    username: meappuser
    password: meappuser
  # url: jdbc:h2:mem:bd_pet

jbs:
  username: YMLUserName
  password: YMLPassword
  jdbcurl: YMLUrl

---
spring:
  config:
    activate:
      on-profile: prod
jbs:
  username: YMLProdUserName
  password: YMLProdPassword
  jdbcurl: YMLProdUrl

---
spring:
  config:
    activate:
      on-profile: dev
jbs:
  username: YMLDevUserName
  password: YMLDevPassword
  jdbcurl: YMLDevUrl

